mydata <- read.table("household_power_consumption.txt", header=TRUE, sep = ';', stringsAsFactors=F)
importdata<-subset(mydata,Date=="1/2/2007" | Date=="2/2/2007")
Date <- as.Date(importdata$Date,"%d/%m/%Y")
Days <- weekdays(Date)
Sub_metering_1 <-as.numeric(importdata$Sub_metering_1)
Sub_metering_2 <-as.numeric(importdata$Sub_metering_2)
Sub_metering_3 <-as.numeric(importdata$Sub_metering_3)

plot(Sub_metering_1,type="l", col = "black",ylab="Energy sub metering", xlab="", xaxt='n')
lines(Sub_metering_2, col = "red",ylab="", xlab="", xaxt='n')
lines(Sub_metering_3, col = "blue",ylab="", xlab="", xaxt='n')
axis(1, at=c(1,length(Days)/2,length(Days)), labels=c("Thur","Fri","Sat"))
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lwd=c(2.5,2.5), col=c("black","red","blue"))
dev.copy(png, file = "plot3.png")
dev.off()
