mydata <- read.table("household_power_consumption.txt", header=TRUE, sep = ';', stringsAsFactors=F)
importdata<-subset(mydata,Date=="1/2/2007" | Date=="2/2/2007")
Date <- as.Date(importdata$Date,"%d/%m/%Y")
Days <- weekdays(Date)
Global_active_power <-as.numeric(importdata$Global_active_power)
plot(Global_active_power, xaxt="n",type="l", ylab="Global Active Power (kilowatts)", xlab="")
axis(1, at=c(1,length(Days)/2,length(Days)), labels=c("Thur","Fri","Sat"))
dev.copy(png, file = "plot2.png")
dev.off()
